services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: frankfurt  # change selon ta localisation (frankfurt, oregon, virginia, singapore)
    branch: master
    image: n8nio/n8n:latest
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
    autoDeploy: true

    envVars:
      - key: N8N_PORT
        value: 5678

      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"

      - key: N8N_BASIC_AUTH_USER
        sync: false  # à définir dans le dashboard Render
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false  # à définir dans le dashboard Render

      - key: N8N_ENCRYPTION_KEY
        sync: false  # à définir toi-même (ex : générer une clé 32 caractères)

      # URL publique de ton app Render (tu la mettras après le 1er déploiement)
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n.onrender.com"

      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true

      - key: GENERIC_TIMEZONE
        value: 'Europe/Paris'

      # Pour connecter une base PostgreSQL Render (optionnel)
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password

    startCommand: |
      chmod 600 /home/node/.n8n/config || true
      n8n start
			
databases:
  - name: n8n-db
    plan: free
